version: '3'

services:
  django:
    build: .
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - internal-caddy

  internal-caddy:
    image: caddy:latest
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile  # Caddy configuration
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - "8080:80"  # Internal Caddy runs on port 8080

volumes:
  static_volume:
  media_volume:
