services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn civic.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - staticfiles:/app/staticfiles
    ports:
      - "8081:80"
    depends_on:
      - django

volumes:
  staticfiles:
