# Generated by Django 5.0.2 on 2024-03-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citywatch', '0004_remove_issuecomment_author_issue_city_issue_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/'),
        ),
    ]
